# Generated by Codex on 2026-04-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                ("video_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("video_file", models.FileField(blank=True, null=True, upload_to="course_videos/%Y/%m/")),
                ("video_url", models.URLField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_preview", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="videos", to="courses.course")),
            ],
            options={
                "db_table": "videos",
                "ordering": ["order", "created_at"],
                "unique_together": {("course", "order")},
            },
        ),
    ]
