# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to="course_videos/%Y/%m/"),
        ),
    ]
