# Generated by Codex on 2026-04-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_video_video_file"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoNote",
            fields=[
                ("note_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp_seconds", models.PositiveIntegerField(default=0)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="video_notes", to="users.studentprofile")),
                ("video", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="videos.video")),
            ],
            options={
                "db_table": "video_notes",
                "ordering": ["timestamp_seconds", "created_at"],
            },
        ),
    ]
