# Generated by Codex on 2026-04-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("videos", "0003_videonote"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoProgress",
            fields=[
                ("progress_id", models.AutoField(primary_key=True, serialize=False)),
                ("watched_seconds", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_watched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="video_progress", to="users.studentprofile")),
                ("video", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="progress_records", to="videos.video")),
            ],
            options={
                "db_table": "video_progress",
                "ordering": ["video__order", "created_at"],
                "unique_together": {("student", "video")},
            },
        ),
    ]
