# Generated by Django 5.2.12 on 2026-04-29 03:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videoprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='course_videos/%Y/%m/'),
        ),
    ]
