# Generated by Django 5.2.12 on 2026-04-29 03:22

import videos.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=videos.storage.LargeVideoCloudinaryStorage(), upload_to='LearnFlow/course_videos/%Y/%m/'),
        ),
    ]
