# Generated by Django 5.2.12 on 2026-05-13 09:37

import videos.models
import videos.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0007_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=videos.storage.LargeVideoCloudinaryStorage(), upload_to=videos.models.video_upload_path),
        ),
    ]
