# Generated by Django 5.2.12 on 2026-04-29 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
        ('videos', '0007_alter_video_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('play', 'Play'), ('pause', 'Pause'), ('ended', 'Ended'), ('seek', 'Seek'), ('skip_forward_10', 'Skip forward 10 seconds'), ('skip_backward_10', 'Skip backward 10 seconds'), ('rate_change', 'Playback speed changed'), ('note_created', 'Note created'), ('note_updated', 'Note updated'), ('note_deleted', 'Note deleted'), ('progress_sync', 'Progress synced')], max_length=40)),
                ('position_seconds', models.PositiveIntegerField(default=0)),
                ('from_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('to_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('delta_seconds', models.IntegerField(default=0)),
                ('playback_rate', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to='users.studentprofile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to='videos.video')),
            ],
            options={
                'db_table': 'learning_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', 'created_at'], name='learning_ev_course__8792ae_idx'), models.Index(fields=['video', 'event_type'], name='learning_ev_video_i_aa2cd1_idx'), models.Index(fields=['student', 'course'], name='learning_ev_student_1c096e_idx')],
            },
        ),
    ]
