# Generated by Django 5.2.12 on 2026-05-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_learning_session_event_telemetry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='learningsession',
            new_name='learning_se_student_13d4f1_idx',
            old_name='learning_se_student_56f780_idx',
        ),
        migrations.RenameIndex(
            model_name='learningsession',
            new_name='learning_se_course__7bbe1c_idx',
            old_name='learning_se_course__67c29d_idx',
        ),
    ]
